Eventosapp/urls.py
from django.urls import path
from . import views
from .views import      EventoListView\
                    ,   EventoDetailView\
                    ,   EventoCreateView\
                    ,   EventoUpdateView\
                    ,   BuscaInvitado\
                    ,   BuscaEvento\
                    ,   InvitadoUpdate\
                    ,   InvitadosUpdate\
                    ,   InvitadoCreate\
                    ,   exportar_invitados\
                    ,   exportar_qrs\
                    ,   etiquetas\
                    ,   etiquetas_msj\
                    ,   invitado_updaterecord\
                    ,   etiquetas_individuales\
                    ,   lista_pdf\
                    ,   lista_pdf_mensaje\
                    #,   Evento_Update\

app_name = "eventos"

urlpatterns = [
    path("", EventoListView.as_view(), name="evento_all"),
    path("evento_create/", EventoCreateView.as_view(), name="evento_create"),
    path("detail/<int:pk>", EventoDetailView.as_view(), name="evento_detail"),
    path("evento_update/<int:pk>", EventoUpdateView.as_view(), name="evento_update"),
    #path("evento_updaterecord/<int:pk>", Evento_Update, name="evento_updaterecord"),
    path("invitados",BuscaEvento,name="invitados"),
    path("evento",BuscaInvitado,name="invitados_detail"),
    path("invitados_update",InvitadosUpdate,name="invitados_update"),
    path("invitado_update/<int:pk>",InvitadoUpdate,name="invitado_update"),
    path("invitado_create/<int:evento_id>",InvitadoCreate.as_view(),name="invitado_create"),
    path('invitados/exportar/<int:pk>', exportar_invitados, name='exportar_invitados'),
    path('invitados/exportarqr/<int:pk>', exportar_qrs, name='exportar_qrinvitados'),
    path('etiquetas/<int:pk>',etiquetas,name='etiquetas'),
    path('etiquetas_msj/<int:pk>',etiquetas_msj,name='etiquetas_msj'),
    path('etiquetas_individuales/<int:pk1>/<int:pk2>',etiquetas_individuales,name='etiquetas_individuales'),
    path('invitado_updaterecord/<int:pk>', invitado_updaterecord, name='invitado_updaterecord'),
    path('lista/<int:pk>',lista_pdf,name='lista_pdf'),
    path('lista_mensaje/<int:pk>',lista_pdf_mensaje,name='lista_pdf_mensaje'),
]

eventos/urls.py
"""
URL configuration for eventos project.

    La lista `urlpatterns` dirige las URL a las vistas. Para obtener más información, consulte:
     https://docs.djangoproject.com/en/5.0/topics/http/urls/
Ejemplos:
Vistas de funciones
     1. Agregue una importación: desde las vistas de importación de my_app
     2. Agregue una URL a urlpatterns: ruta('', views.home, nombre='home')
Vistas basadas en clases
     1. Agregue una importación: desde other_app.views import Inicio
     2. Agregue una URL a urlpatterns: ruta('', Home.as_view(), nombre='home')
Incluyendo otra URLconf
     1. Importe la función include(): desde django.urls importe include, ruta
     2. Agregue una URL a urlpatterns: ruta('blog/', include('blog.urls'))
"""
from django.contrib import admin
from django.urls import path
from django.urls import include
from .views import LandingPage



urlpatterns = [
    path('admin/', admin.site.urls),
    path('',LandingPage.as_view(),name="Landing_page"),
    path("eventos/",include("Eventosapp.urls")),
]

urls.py
"""
URL configuration for eventos project.

    La lista `urlpatterns` dirige las URL a las vistas. Para obtener más información, consulte:
     https://docs.djangoproject.com/en/5.0/topics/http/urls/
Ejemplos:
Vistas de funciones
     1. Agregue una importación: desde las vistas de importación de my_app
     2. Agregue una URL a urlpatterns: ruta('', views.home, nombre='home')
Vistas basadas en clases
     1. Agregue una importación: desde other_app.views import Inicio
     2. Agregue una URL a urlpatterns: ruta('', Home.as_view(), nombre='home')
Incluyendo otra URLconf
     1. Importe la función include(): desde django.urls importe include, ruta
     2. Agregue una URL a urlpatterns: ruta('blog/', include('blog.urls'))
"""
from django.contrib import admin
from django.urls import path
from django.urls import include
from .views import LandingPage



urlpatterns = [
    path('admin/', admin.site.urls),
    path('',LandingPage.as_view(),name="Landing_page"),
    path("eventos/",include("Eventosapp.urls")),
]

Eventosapp/models.py
from django.db import models
import os, qrcode
from django.core.files import File
from django.core.exceptions import ValidationError

def validate_video(value):
    if not value.name.endswith('.mp4'):
        raise ValidationError('Solo se permiten archivos MP4 para video.')
    
def validate_imagen(value):
    if not value.name.endswith('.jpeg'):
        raise ValidationError('Solo se permiten archivos JPEG para imagen.')
    
# Create your models here.
class Evento(models.Model):
    idEvento = models.AutoField(primary_key=True)
    descripcion = models.CharField(max_length=50, null=False,verbose_name='Nombre')
    fechaInicio = models.DateTimeField(null=False, verbose_name='fecha')
    lugar = models.CharField(max_length=30,null= False,verbose_name='Lugar')
    activo  = models.BooleanField(default=True,verbose_name='Activo')
    video = models.FileField(upload_to='video/',null=True,blank=True, validators=[validate_video], error_messages={'invalid': 'Solo se permiten archivos MP4 para video.'})
    imagen = models.FileField(upload_to='img/',null=True,blank=True, validators=[validate_imagen], error_messages={'invalid': 'Solo se permiten archivos JPEG para imagen.'})

    class Meta:
        db_table = "eventos"

    def __str__(self):
        return f"Evento: {self.descripcion} {self.fechaInicio} lugar {self.lugar}"
    
    def get_fields(self):
        return [
            (field.verbose_name, field.value_from_object(self))
            for field in self.__class__._meta.fields[1:]
        ]
    


class Invitados(models.Model):
    idInvitado = models.AutoField(primary_key=True)
    nombre = models.CharField(max_length=70, null=False, verbose_name='Nombre',blank=False)
    idEvento = models.ForeignKey(Evento,on_delete=models.CASCADE,null=False,blank=False)
    ingreso = models.BooleanField(verbose_name='Ingresó', null=False,default=False)
    hora_ingreso = models.TimeField(verbose_name='Hora de Ingreso', null=True,blank=True)
    qr = models.ImageField(upload_to='qr', null=True, blank=True)
    mensaje = models.CharField(max_length=200, null=True, blank=True)

    class Meta:
        verbose_name='invitado'
        verbose_name_plural='invitados'
        db_table = 'invitados'
    
    

    def generate_qr(self):
        # Generar el código QR con los datos del invitado y el evento
        qr = qrcode.QRCode(
            version=1,
            error_correction=qrcode.constants.ERROR_CORRECT_H,
            box_size=10,
            border=4,
        )
        qr.add_data(f"{self.idInvitado}-{self.idEvento}-Invitado: {self.nombre}\nEvento: {self.idEvento.descripcion}\n @2004 SSCOM INFORMATICA - DERECHOS RESERVADOS")
        qr.make(fit=True)

        # Convertir a PIL.Image
        img = qr.make_image(fill_color="black", back_color=(255, 255, 255))

        # Guardar la imagen en un archivo temporal
        filename = f'qr_{self.idInvitado}.jpg'
        img.save(filename, format="JPEG")

        # Guardar la imagen en el campo qr del modelo Invitados
        self.qr.save(filename, File(open(filename, 'rb')))

        # Eliminar el archivo temporal
        os.remove(filename)

    def __str__(self):
        fila = "Invitado: " + str(self.nombre) + " - " + " Evento: " + str(self.idEvento.descripcion) + " - " +" Ingreso: " + str(self.ingreso) +" - " + " Hora: " + str(self.hora_ingreso) + " - " +" IdEvento: " + str(self.idEvento.idEvento)+ " - " + " Mensaje: " + str(self.mensaje)
        return fila
    
    def get_fields(self):
        return [
            (field.verbose_name, field.value_from_object(self))
            for field in self.__class__._meta.fields[1:]
        ]
    

Eventosapp/views.py
import csv, os
from django.shortcuts               import render,get_object_or_404
from django.urls                    import reverse_lazy
from django.views.generic           import TemplateView
from django.views.generic.list      import ListView
from django.views.generic.detail    import DetailView
from django.views.generic.edit      import CreateView, UpdateView, DeleteView
from django.db                      import models
from django.shortcuts               import render, redirect
from django.views                   import View

from django.db.models import Q

from .models                        import Evento, Invitados

from django.http import HttpResponse, HttpResponseRedirect
import cv2
from pyzbar.pyzbar import decode
from django.core.files.base import ContentFile
from datetime import datetime
from .models import Invitados
import qrcode
from io import BytesIO
import base64
import zipfile
from PIL import Image
from reportlab.pdfgen import canvas
from reportlab.lib.pagesizes import A4
from reportlab.lib.units import cm
from django.core.files.storage import FileSystemStorage
from django.conf import settings
# Create your views here.

class EventoBaseView(View):
    """ESTA CLASE NO SE PONE EN LAS URLS"""
    template_name = "evento.html"
    model         = Evento
    fields        = "__all__"
    success_url = reverse_lazy("eventos:evento_all")

class EventoListView(EventoBaseView,ListView):
    context_object_name = 'eventos'
    
class EventoDetailView(EventoBaseView,DetailView):
    template_name = "eventos_detail.html"
    extra_content={"Titulo" : "Detalle del Evento"}

    
class EventoCreateView(EventoBaseView,CreateView):
    template_name = "eventoscreate.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['Titulo'] = "CREA UN NUEVO EVENTO"
        context['tipo'] = "Crear Evento"
        return context
    
    
class EventoUpdateView(EventoBaseView,UpdateView):
    template_name = "eventoupdate.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['Titulo'] = "Actualiza el Evento"
        context['tipo'] = "Actualiza Evento"
        return context

#def Evento_Update(request, pk):
#    evento = Evento.objects.get(idEvento=pk)
#    todo = request.POST
#    print(todo)
#    descripcion = request.POST['descripcion']
#    lugar = request.POST['lugar']
#    fechainicio = request.POST['fechaInicio']
#    video = request.POST['video']
#    imagen = request.POST['imagen']
#    evento.descripcion = descripcion
#    evento.lugar = lugar
#    evento.fechaInicio = fechainicio
#    if video:
#        evento.video = video
#    if imagen:
#        evento.imagen = imagen
#    evento.save()
#    return redirect('eventos:evento_all')

                                                     
"""class InvitadosView(ListView):
    
    invitados = Invitados.objects.all()
    eventos = Evento.objects.all()
    template_name = "invitado.html"
    extra_content = {'invitados':invitados,
                     'evento_list':eventos
    }
    success_url   = reverse_lazy('ordenes:invitados')

    def get_queryset(self):
        return Invitados.objects.all()"""
    
def BuscaEvento(request):
    
    if request.method == 'POST':
        buscar_evento = request.POST.get("evento")            
        evento_buscado = Evento.objects.filter(idEvento=buscar_evento)
        return render(request, 'pantalla.html',{'evento_buscado':evento_buscado})
    if request.method == 'GET':         
        evento_list = Evento.objects.filter(activo=True)
        return render(request, 'invitado.html',{'evento_list':evento_list})

    
"*** P A N T A L L A ***"
def BuscaInvitado(request):
    invitados =Invitados.objects.all()
    if request.method == 'POST':
        buscar_invitado = request.POST.get("updateinvitado")
        buscar_evento = request.POST.get("eventoseleccionado")
        qr = buscar_invitado.split('-')
        
        eventoprincipal = Evento.objects.filter(idEvento=buscar_evento)
        
        buscar_invitado=qr[0]
        if buscar_invitado:
            invitadosBuscados = Invitados.objects.filter(idInvitado=buscar_invitado,idEvento=buscar_evento)
            for i in invitadosBuscados:
                ingresodeinvitado = i.ingreso
                horaingreso = i.hora_ingreso
                msj = i.mensaje
            if msj == "None":
                msj = ""
            if invitadosBuscados:
                print(invitadosBuscados)
                if ingresodeinvitado:
                
                    mensaje="Ud . ya ingresó al evento a  las "+str(horaingreso.strftime('%H:%M'))+" hrs."
                    mensajepersonal =""
                else:
                    invitadosBuscados.update(ingreso=True, hora_ingreso=datetime.now())
                    mensaje="Gracias por venir !!"
                    mensajepersonal =msj
                print("coincidencia", mensajepersonal)
                return render(request, 'pantalla.html',{'invitado_buscado':invitadosBuscados,'evento_buscado':eventoprincipal,'mensaje':mensaje,'mensajepersonal':mensajepersonal})
            else:
                print("sin coincidencia")
                mensaje="Ud. no tiene acceso a este evento"
                return render(request, 'pantalla.html',{'invitado':invitados,'evento_buscado':eventoprincipal,'mensaje':mensaje})           
        else:
            return render(request, 'pantalla.html',{'invitado':invitados,'evento_buscado':eventoprincipal})


def InvitadosUpdate(request):
    eventos = Evento.objects.all()
    evento_list = Evento.objects.filter(activo=True)
    if request.method == 'POST':
        buscar_evento = request.POST.get("eventoupdate")
        #obtener el id del evento a partir de su nombre
        if buscar_evento:
            invitados = Invitados.objects.filter(idEvento=buscar_evento)
            evento = Evento.objects.filter(idEvento=buscar_evento)
            print(buscar_evento)
            return render(request, 'invitadosupdate.html',{'evento_list':evento_list,'invitados':invitados,
                                                           'evento_buscado':buscar_evento,"evento":evento})


    if request.method == 'GET':         
        return render(request, 'invitadosupdate.html',{'evento_list':evento_list})


class InvitadoBaseView(View):
    model=Invitados
    fields        = "__all__"
    success_url   = reverse_lazy('eventos:invitados_update')

def InvitadoUpdate(request,pk):
    invitado = get_object_or_404(Invitados, idInvitado=pk)
    return render(request, 'invitadoupdate.html',{"tipo": "Actualizar Invitado","invitado":invitado})
    
def invitado_updaterecord(request, pk):
    invitado = Invitados.objects.get(idInvitado=pk)
    ingreso = request.POST['ingreso']
    mensaje = request.POST['mensaje']
    nombre = request.POST['nombre']
    buscar_evento = request.POST['idEvento']
    invitado.ingreso = ingreso
    invitado.mensaje = mensaje
    invitado.nombre = nombre
    invitado.save()
    evento_list = Evento.objects.filter(activo=True)
    invitados = Invitados.objects.filter(idEvento=buscar_evento)
    evento = Evento.objects.filter(idEvento=buscar_evento)
    return render(request, 'invitadosupdate.html',{'evento_list':evento_list,'invitados':invitados,
                                                'evento_buscado':buscar_evento,"evento":evento})



class InvitadoCreate(InvitadoBaseView,CreateView):
    template_name='invitadocreate.html'
    evento_list = Evento.objects.filter(activo=True)
    extra_context = {"tipo": "Aceptar","evento_list":evento_list}
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['evento_id'] = self.kwargs.get('evento_id',None)
        context['evento'] = Evento.objects.get(idEvento=self.kwargs.get('evento_id')).descripcion
        return context
    
    def form_valid(self, form):
        response = super().form_valid(form)
        invitado = form.save(commit=False)
        invitado.generate_qr()
        invitado.save()
        evento_list = Evento.objects.filter(activo=True)
        buscar_evento = self.kwargs.get('evento_id',None)
        invitados = Invitados.objects.filter(idEvento=buscar_evento)
        evento = Evento.objects.filter(idEvento=buscar_evento)
        return render(self.request, 'invitadosupdate.html', {'evento_list':evento_list,'invitados':invitados,
                                                'evento_buscado':buscar_evento,"evento":evento})
## ///////// NO LO USO  ///////////
def exportar_invitados(request,pk):
    response = HttpResponse(content_type='text/csv')
    response['Content-Disposition'] = 'attachment; filename="invitados.csv"'

    writer = csv.writer(response)
    writer.writerow(['IdInvito','IdEvento','Nombre', 'Evento','Fecha del Evento','Hora de ingreso', 'Ingresó'])

    invitados = Invitados.objects.filter(idEvento=pk)
    for invitado in invitados:
        writer.writerow([invitado.idInvitado,invitado.idEvento.idEvento,invitado.nombre,invitado.idEvento.descripcion,invitado.idEvento.fechaInicio  ,invitado.hora_ingreso, invitado.ingreso])

    return response


## ///// NO LO USO ///////////
def exportar_qrs(request, pk):
    response = HttpResponse(content_type='application/zip')
    zip_filename = 'qrs.zip'
    response['Content-Disposition'] = f'attachment; filename={zip_filename}'
    zip = zipfile.ZipFile(response, 'w')

    invitados = Invitados.objects.filter(idEvento=pk)
    for invitado in invitados:
        qr_filename = f'qr_{invitado.idInvitado}.jpg'
        qr_image = generate_qr_image(invitado.idInvitado, pk, qr_filename)
        zip.writestr(qr_filename, qr_image)

    zip.close()
    return response

def generate_qr_image(invitado_id, evento_id, filename):
    invitado = Invitados.objects.get(idInvitado=invitado_id)
    evento = Evento.objects.get(idEvento=evento_id)

Eventosapp/templates/evento.html
{% extends 'base_template.html' %}
{% block content %}

<main>
    <div class="container">
        <h1>LISTA DE EVENTOS</h1>
        <form method="POST" action="{% url 'eventos:evento_create'%}">
            {% csrf_token %}
            <button type="submit" class="btn">Nuevo Evento</button>
        </form>
        <table class="table table-primary">
            <thead>
                <tr>
                    <th scope="col">ID</th>
                    <th scope="col">EVENTO</th>
                    <th scope="col">LUGAR</th>
                    <th scope="col">FECHA</th>
                    <th scope="col">ACTIVO</th>
                    <th scope="col">VIDEO</th>
                    <th scope="col">FONDO DE TARJETA</th>
                    <th scope="col">EDICION</th>
                    <th scope="col">INVITADOS PDF</th>
                    <th scope="col">INVITADOS PDF C/MSJ</th>
                    <th scope="col">TARJETAS</th>
                    <th scope="col">TARJETAS c/MSJ</th>
                </tr>
            </thead>
            <ul>
            {% for evento in eventos %}
            <tbody>
                <td scope="row">{{evento.idEvento}}</td>
                <td>{{evento.descripcion}}</td>
                <td>{{evento.lugar}}</td>
                <td>{{evento.fechaInicio | date:"d/m/Y H:i"}}</td>
                {% if  evento.activo %}
                    <td style="color: green">SI</td>
                {% else %}
                    <td  style="color: red">NO</td>
                {% endif %}
                {% if evento.video %}
                    <td>
                        <video class="miniatura" controls>
                        <source src="{{ evento.video.url }}" type="video/mp4">
                        Tu navegador no soporta video HTML5
                        </video>
                    </td>
                {% else %}
                    <td>No hay video</td>
                {% endif %}
                {% if evento.imagen %}
                    <td><img src="{{ evento.imagen.url }}" width="120px"></td>
                {% else %}
                    <td>No hay imagen</td>
                {% endif %}
                <td>
                    <form method="POST" action="{% url 'eventos:evento_update' evento.idEvento %}">
                        {% csrf_token %}
                        <button type="submit" class="btn">Editar</button>
                    </form>
                </td>
                <!--
                <td>
                    <form method="POST" action="{% url 'eventos:exportar_invitados' evento.idEvento %}">
                        {% csrf_token %}
                        <button type="submit" class="btn">Exportar lista</button>
                    </form>
                </td>
                -->
                <td>
                    <form method="POST" action="{% url 'eventos:lista_pdf' evento.idEvento %}">
                        {% csrf_token %}
                        <button type="submit" class="btn">lista en PDF</button>
                    </form>
                </td>
                <td>
                    <form method="POST" action="{% url 'eventos:lista_pdf_mensaje' evento.idEvento %}">
                        {% csrf_token %}
                        <button type="submit" class="btn">lista en PDF c/Mensaje</button>
                    </form>
                </td>
                <!--
                <td>
                    <form method="POST" action="{% url 'eventos:exportar_qrinvitados' evento.idEvento %}">
                        {% csrf_token %}
                        <button type="submit" class="btn">Exportar QR</button>
                    </form>
                </td>
                -->
                <td>
                    <form method="POST" action="{% url 'eventos:etiquetas' evento.idEvento %}">
                        {% csrf_token %}
                        <button type="submit" class="btn">Tarjetas</button>
                    </form>
                </td>
                <td>
                    <form method="POST" action="{% url 'eventos:etiquetas_msj' evento.idEvento %}">
                        {% csrf_token %}
                        <button type="submit" class="btn">Tarjetas c/msj</button>
                    </form>
                </td>
            {% empty %}
                <li>No hay eventos para mostrar.</li>
            </tbody>
            {% endfor %}
        </table>
    </div>
</main>

{% endblock %}

Eventosapp/templates/eventoscreate.html
{% extends "base_template.html" %}
{% block content %}
{% load static %}
   
<div class="card">
    <div class="card-header">
        <h4  style="text-align: center;">{{ Titulo }}</h4>
    </div>
    <div class="card-body">

        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <!--{{form.as_p}}-->
            <!-- Usa form.erros para detectar el error en los campos -->
            <!--{{ form.errors }}-->
            {% if form.non_field_errors %}
                <div class="alert alert-danger">
                    {{ form.non_field_errors }}
                </div>
            {% endif %}
            <div class="label-input">
                <p>
                    <label for="id_nombre">Nombre</label>
                    <input type="text" name="descripcion" required="True" id="id_nombre" maxlength="70"
                        style="width: 400px;">
                </p>
                <p>
                    <label for="id_hora">Lugar del Evento:</label>
                    <input type="text" name="lugar" id="id_hora" style="width: 300px;">
                </p>
                <p>
                    <label for="id_evento">Fecha del Evento:</label>

                    <input type="datetime" name="fechaInicio" id="id_evento" style="width: 150px"
                    placeholder="aaaa-mm-dd hh:mm">
                </p>
                <p>
                    <label for="video">Video del Evento:</label>
                    {{ form.video.errors }}
                    <input type="file" name="video" id="video" style="width: auto" accept="video/mp4"
                    placeholder="suba el video del evento">
                </p>
                <p>
                    <label for="imagen">Fondo de la tarjeta:</label>
                    {{ form.imagen.errors }}
                    <input type="file" name="imagen" id="imagen" style="width: auto" accept="image/jpeg"
                    placeholder="suba la imagen de fondo de la tarjeta">
                </p>
                <p>
                    <label for="id_ingreso">Activo:</label>
                    <input type="checkbox" name="activo" id="id_ingreso" checked>
                </p>
            </div>
            <div class="label-btn">
                <input type="submit" value="{{ tipo }}" class="btn" >
            </div>
        </form>
    </div>
</div>
{% endblock %}

Eventosapp/templates/invitadosupdate.html
{% extends "base_template.html" %}
{% block content %}
{% load static %}
   
<div class="-body">
    <h1>Lista de Invitados</h1>
    <form class="card-body" method="POST" action="{% url 'eventos:invitados_update' %}">    {% csrf_token %}
        <p>
            <select name="eventoupdate" class="form-control" required>
              {% for evento in evento_list %}
              <option value="{{ evento.idEvento }}">{{ evento.descripcion }}</option>
              {% endfor %}
            </select>
        </p>
        <div class="label-btn">
          <input type="submit" value="Buscar" class="btn" style="height: 40px;" />
        </div>
    </form>
    {% if evento %}
        <div class="card">
            
        <table>
            {% for evento in evento %}
            <div class="card">
                <h3>{{ evento.descripcion }}</h3>
            </div>
            <div>
                <form method="POST" action="{% url 'eventos:etiquetas' evento.idEvento %}">
                    {% csrf_token %}
                    <button type="submit" class="btn">Ver Tarjetas</button>
                </form>
                <form method="POST" action="{% url 'eventos:invitado_create' evento.idEvento %}">
                    {% csrf_token %}
                    <input type="hidden" name="evento_id" value="{{ evento.idEvento }}">
                    <button type="submit" class="btn">Nuevo invitado</button>
                </form>
            </div>
            {% endfor %}
            
            {% if invitados %}
            
                <thead>
                    <tr>
                        <th>ID INVITADO</th>
                        <th>EVENTO</th>
                        <th>NOMBRE</th>
                        <th>MENSAJE PERSONALIZADO</th>
                        <th>INGRESO</th>
                        <th>HORA DE INGRESO</th>
                        <th>QR CODE</th>
                        <th>EDICION</th>
                        <th>TARJETA</th>
                    </tr>
                </thead>
            
                <tbody>
                    {% for invitado in invitados %}
                    <tr>
                        <td>{{ invitado.idInvitado }}</td>
                        <td class="item_listado">{{ invitado.idEvento.descripcion }}</td>
                        <td>{{ invitado.nombre }}</td>
                        <td>{{ invitado.mensaje }}</td>
                        {% if invitado.ingreso %}
                        <td class="item_listado">{{ invitado.idEvento.descripcion }}</td>
                            <td class="verde-negrita item_listado">SI</td>
                        {% else %}
                            <td class="rojo-negrita item_listado">NO</td>
                        {% endif %}
                        <td class="item_listado">{{ invitado.hora_ingreso|date:'H:i:s' }}</td>
                        <td><img src="{% static 'media/img/' %}{{ invitado.qr }}" width="70px" alt="QR Code"></td>
                        <td class="item_listado">
                            <form method="POST" action="{% url 'eventos:invitado_update' invitado.idInvitado %}">
                                {% csrf_token %}
                                <button type="submit" class="btn">Editar</button>
                            </form>
                        </td>
                        <td class="item_listado">
                            <form method="POST" action="{% url 'eventos:etiquetas_individuales' invitado.idEvento.idEvento invitado.idInvitado %}">
                                {% csrf_token %}
                                <button type="submit" class="btn">Tarjeta</button>
                            </form>
                        </td>
                    <tr>
                    {% endfor %}                
                </tbody>
            {% endif %}    
    
        </table>
        </div>
    {% endif %}
</div>    

{% endblock %}

Eventosapp/templates/invitadoupdate.html
{% extends "base_template.html" %}
{% block content %}

   
<div class="card">
    <div class="card-header">
        <h4  style="text-align: center;">EDITAR INVITADO</h4>
    </div>
    <div class="card-body">

        <form action="{% url 'eventos:invitado_updaterecord' invitado.idInvitado %}" method="post" >
            {% csrf_token %}
            <!--{{form.as_p}}-->
            <!-- Usa form.erros para detectar el error en los campos -->
            <!--{{ form.errors }}-->
            
            <div class="label-input">
                <p>
                    <label for="id_nombre">Nombre</label>
                    <input type="text" name="nombre" required="True" id="id_nombre" maxlength="70"
                        value="{{ invitado.nombre }}" style="width: 400px;background-color:transparent; color: green;">
                </p>
                <p>
                    <label for="id_mensaje">Mensaje Personalizado</label>
                    <input type="text" name="mensaje" id="id_mensaje" maxlength="200"
                        value="{{ invitado.mensaje }}" style="width: 400px;background-color:transparent; color: green;" >
                </p>
                <p>
                    <label for="id_evento">Evento</label>
                    <input type="hidden" name="idEvento" required="True" id="id_evento"
                        value="{{ invitado.idEvento.idEvento }}" >
                    <input type="text" name="NombreEvento" required="True" id="id_evento"
                        value="{{ invitado.idEvento.descripcion }}" style="width: 410px;background-color:transparent;color: grey;" readonly>
                </p>
                <p>
                    <label for="id_hora">Hora de ingreso:</label>
                    <input type="text" name="hora_ingreso" id="id_hora"
                        value="{{ invitado.hora_ingreso|date:'H:i:s' }}" style="width: 340px;background-color:transparent;color: grey;" readonly>
                </p>
                <p>
                    <label for="id_ingreso">Ingresó:</label>
                    
                    <!--<input type="checkbox" name="ingreso" id="id_ingreso" checked="">-->
                    <select name="ingreso" id="id_ingreso" class="form-control">
                        {% if invitado.ingreso %}
                        <option value="True" selected >SI</option>
                        <option value="False" >NO</option>
                        {% else %}
                        <option value="True" >SI</option>
                        <option value="False" selected >NO</option>
                        {% endif %}
                    </select>
                </p>
                
            </div>
            <div class="label-btn">
                <input type="submit" value="{{ tipo }}" class="btn" >
            </div>
        </form>
    </div>
</div>
{% endblock %}