Eventosapp/urls.py
from django.urls import path
from . import views
from .views import      EventoListView\
                    ,   EventoDetailView\
                    ,   EventoCreateView\
                    ,   EventoUpdateView\
                    ,   BuscaInvitado\
                    ,   BuscaEvento\
                    ,   InvitadoUpdate\
                    ,   InvitadosUpdate\
                    ,   InvitadoCreate\
                    ,   exportar_invitados\
                    ,   exportar_qrs\
                    ,   etiquetas\
                    ,   etiquetas_msj\
                    ,   invitado_updaterecord\
                    ,   etiquetas_individuales\
                    ,   lista_pdf\
                    ,   lista_pdf_mensaje\
                    #,   Evento_Update\

app_name = "eventos"

urlpatterns = [
    path("", EventoListView.as_view(), name="evento_all"),
    path("evento_create/", EventoCreateView.as_view(), name="evento_create"),
    path("detail/<int:pk>", EventoDetailView.as_view(), name="evento_detail"),
    path("evento_update/<int:pk>", EventoUpdateView.as_view(), name="evento_update"),
    #path("evento_updaterecord/<int:pk>", Evento_Update, name="evento_updaterecord"),
    path("invitados",BuscaEvento,name="invitados"),
    path("evento",BuscaInvitado,name="invitados_detail"),
    path("invitados_update",InvitadosUpdate,name="invitados_update"),
    path("invitado_update/<int:pk>",InvitadoUpdate,name="invitado_update"),
    path("invitado_create/<int:evento_id>",InvitadoCreate.as_view(),name="invitado_create"),
    path('invitados/exportar/<int:pk>', exportar_invitados, name='exportar_invitados'),
    path('invitados/exportarqr/<int:pk>', exportar_qrs, name='exportar_qrinvitados'),
    path('etiquetas/<int:pk>',etiquetas,name='etiquetas'),
    path('etiquetas_msj/<int:pk>',etiquetas_msj,name='etiquetas_msj'),
    path('etiquetas_individuales/<int:pk1>/<int:pk2>',etiquetas_individuales,name='etiquetas_individuales'),
    path('invitado_updaterecord/<int:pk>', invitado_updaterecord, name='invitado_updaterecord'),
    path('lista/<int:pk>',lista_pdf,name='lista_pdf'),
    path('lista_mensaje/<int:pk>',lista_pdf_mensaje,name='lista_pdf_mensaje'),
]

eventos/urls.py
"""
URL configuration for eventos project.

    La lista `urlpatterns` dirige las URL a las vistas. Para obtener más información, consulte:
     https://docs.djangoproject.com/en/5.0/topics/http/urls/
Ejemplos:
Vistas de funciones
     1. Agregue una importación: desde las vistas de importación de my_app
     2. Agregue una URL a urlpatterns: ruta('', views.home, nombre='home')
Vistas basadas en clases
     1. Agregue una importación: desde other_app.views import Inicio
     2. Agregue una URL a urlpatterns: ruta('', Home.as_view(), nombre='home')
Incluyendo otra URLconf
     1. Importe la función include(): desde django.urls importe include, ruta
     2. Agregue una URL a urlpatterns: ruta('blog/', include('blog.urls'))
"""
from django.contrib import admin
from django.urls import path
from django.urls import include
from .views import LandingPage



urlpatterns = [
    path('admin/', admin.site.urls),
    path('',LandingPage.as_view(),name="Landing_page"),
    path("eventos/",include("Eventosapp.urls")),
]

urls.py
"""
URL configuration for eventos project.

    La lista `urlpatterns` dirige las URL a las vistas. Para obtener más información, consulte:
     https://docs.djangoproject.com/en/5.0/topics/http/urls/
Ejemplos:
Vistas de funciones
     1. Agregue una importación: desde las vistas de importación de my_app
     2. Agregue una URL a urlpatterns: ruta('', views.home, nombre='home')
Vistas basadas en clases
     1. Agregue una importación: desde other_app.views import Inicio
     2. Agregue una URL a urlpatterns: ruta('', Home.as_view(), nombre='home')
Incluyendo otra URLconf
     1. Importe la función include(): desde django.urls importe include, ruta
     2. Agregue una URL a urlpatterns: ruta('blog/', include('blog.urls'))
"""
from django.contrib import admin
from django.urls import path
from django.urls import include
from .views import LandingPage



urlpatterns = [
    path('admin/', admin.site.urls),
    path('',LandingPage.as_view(),name="Landing_page"),
    path("eventos/",include("Eventosapp.urls")),
]

templates/base_template.html
{% load static %}

<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!--
    <script src="https://code.jquery.com/jquery-3.7.0.js"
        integrity="sha256-JlqSTELeR4TLqP0OG9dxM7yDPqX1ox/HfgiSLBj8+kM=" crossorigin="anonymous">
    </script>
    -->
    <title>Eventos</title>
    <!--
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet">
    -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}" />
    
    
</head>
<body>
    <nav class="navbar">
        <div class="collapse">
            <ul class="navbar-nav">
                <li><a href="{% url 'Landing_page' %}">CONTROL DE ACCESO</a></li>                 
                <li><a href="{% url 'eventos:evento_all' %}">EVENTOS</a></li>
                <li><a href="{% url 'eventos:invitados_update' %}">INVITADOS</a></li>
                <li><a href="{% url 'eventos:invitados' %}">EVENTO PRINCIPAL</a></li>
            </ul>
        </div>
    </nav>
    <center>
        {% block content%} {% endblock %}
    </center>
   
    <script type="text/javascript" src="{% static 'js/script.js' %}"></script>
</body>
</html>